### ISSUE TITLE
Need  a little help getting the docker install to work on my EX4100

### ISSUE THREAD

**Issue by smcfadden** [JediNite/docker-ce-WDEX4100-binaries#1]
Hi 
Tried following the Readme script but don't get the same response as depicted. I am completely new to this.  directory containing files is created with correct files but the executable gives different results. See listing. Any help welcome.
[Listing.txt](https://github.com/JediNite/docker-ce-WDEX4100-binaries/files/10200902/Listing.txt)

**Comment by JediNite** [comment]
Hi,

To get access to these packages, you will also need to install Entware.  Check out https://github.com/Entware/Entware and https://github.com/WDCommunity/wdpksrc/releases/tag/entware-v1.05.

Cheers,

JediNite

**Comment by smcfadden** [comment]
ThanksSent from Outlook for AndroidFrom: JediNite ***@***.***>Sent: Monday, 26 December 2022, 06:56To: JediNite/docker-ce-WDEX4100-binaries ***@***.***>Cc: smcfadden ***@***.***>; Author ***@***.***>Subject: Re: [JediNite/docker-ce-WDEX4100-binaries] Need  a little help getting the docker install to work on my EX4100 (Issue #1)
Hi,
To get access to these packages, you will also need to install Entware.  Check out https://github.com/Entware/Entware.
Cheers,
JediNite

**Comment by JediNite** [comment]
No updates for several months.
